# Generated by Django 5.1.9 on 2025-05-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_credit_gig_job_application_message_notification_and_more"),
    ]

    operations = []
