# Generated by Django 5.1.9 on 2025-05-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_review_model"),
    ]

    operations = []
