# Generated by Django 5.1.9 on 2025-06-22 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_remove_job_location_remove_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total amount of the order, including tax and shipping.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated.')),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates if the order has been successfully paid for.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who placed the order. Can be null for guest orders.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='Your internal unique transaction ID for this payment attempt.', max_length=100, null=True, unique=True)),
                ('bank_transaction_id', models.CharField(blank=True, help_text='The transaction ID returned by SSLCommerz (or other payment gateway).', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount processed in this payment transaction.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled by User'), ('VALIDATED', 'Validated by API'), ('RISK', 'Risk Payment')], default='PENDING', help_text='Current status of the payment transaction.', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text="Method used for payment (e.g., 'VISA', 'Mastercard', 'Bkash').", max_length=50, null=True)),
                ('currency', models.CharField(default='BDT', help_text='Currency of the payment (e.g., BDT, USD).', max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment record was created.')),
                ('validation_status', models.CharField(blank=True, help_text='Detailed validation status from the payment gateway.', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Any error message associated with a failed payment.', null=True)),
                ('order', models.ForeignKey(help_text='The order associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
