# Generated by Django 5.1.9 on 2025-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., City, Country or Region', max_length=255, null=True),
        ),
    ]
