# Generated by Django 5.1.9 on 2025-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.TextField(),
        ),
    ]
