# Generated by Django 5.1.9 on 2025-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_job_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='subject',
            field=models.TextField(),
        ),
    ]
