# Generated by Django 5.1.9 on 2025-06-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_gig_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='subjects',
        ),
    ]
