# Generated by Django 5.1.9 on 2025-06-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_gig_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
