# Generated by Django 5.1.9 on 2025-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chat_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='gigs_as_job', to='core.subject'),
        ),
    ]
