# Generated by Django 5.1.9 on 2025-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_notification_user_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_balance',
            field=models.IntegerField(default=5),
        ),
    ]
