# Generated by Django 5.1.9 on 2025-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
