# Generated by Django 5.1.9 on 2025-06-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_contact_unlocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
