# Generated by Django 5.1.9 on 2025-06-26 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_unlocked',
        ),
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'tutor')},
            },
        ),
    ]
