# Generated by Django 5.1.9 on 2025-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_bio_user_education_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
