# Generated by Django 5.1.9 on 2025-06-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_jobcount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='job',
        ),
    ]
