# Generated by Django 5.1.9 on 2025-07-25 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_conversation_message_conversationparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Per Hour', 'Per Hour'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Year', 'Per Year')], default='Fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in kilometers if Travel to Tutor', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='Primary', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='service_type',
            field=models.CharField(choices=[('Tutoring', 'Tutoring'), ('Assignment Help', 'Assignment Help')], default='Tutoring', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='subjects',
            field=models.ManyToManyField(related_name='jobs', to='core.subject'),
        ),
    ]
