# Generated by Django 5.1.9 on 2025-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_job_is_active_remove_job_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageread',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=10),
        ),
    ]
