# Generated by Django 5.1.9 on 2025-08-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_messageread_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='teacher',
        ),
        migrations.AddField(
            model_name='gig',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='fee_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gig',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='used_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
