# Generated by Django 5.1.9 on 2025-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_gig_contact_info_remove_gig_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
