# Generated by Django 5.1.9 on 2025-08-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gig_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Total hours for the job', null=True),
        ),
    ]
