# Generated by Django 5.1.9 on 2025-08-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_job_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryGroupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5, unique=True)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PointPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_points', models.PositiveIntegerField()),
                ('bonus_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnlockPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave null for no upper limit', max_digits=10, null=True)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='core.job')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'tutor')},
            },
        ),
    ]
