# Generated by Django 5.1.9 on 2025-08-22 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_countrygroup_countrygrouppoint_pointpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
