# Generated by Django 5.1.9 on 2025-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
