# Generated by Django 4.2.24 on 2025-09-20 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_premium_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactunlock',
            old_name='tutor',
            new_name='target',
        ),
        migrations.AlterUniqueTogether(
            name='contactunlock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contactunlock',
            name='unlocker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_unlocked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contactunlock',
            unique_together={('unlocker', 'target')},
        ),
        migrations.RemoveField(
            model_name='contactunlock',
            name='student',
        ),
    ]
