# Generated by Django 4.2.27 on 2025-12-30 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_review_options_rename_teacher_review_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_given_referral_bonus',
            field=models.BooleanField(default=False, help_text="Whether the referrer has received the bonus for this user's first purchase"),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The user who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
